language: rust
dist: xenial

cache: cargo

os:
  - linux
  - osx

rust:
  - 1.39.0
  - nightly

script:
  - cargo build --verbose --all --exclude benchmarks
  - cargo test --verbose --all --exclude benchmarks
  - cargo run -p tests-alloc --verbose
  - if [[ $TRAVIS_RUST_VERSION = nightly* ]]; then
      cargo bench --verbose --no-run;
    fi

addons:
  homebrew:
    packages:
      - cmake
      - ninja
  apt:
    packages:
      - cmake
      - ninja-build
