[package]
name = "tests-infra"
version = "0.0.0"
authors = ["Dan Burkert <dan@danburkert.com>"]
publish = false
edition = "2018"

[lib]
doctest = false

[dependencies]
bytes = { version = "0.5", default-features = false }
cfg-if = "0.1"
prost = { path = "..", default-features = false }
