[package]
name = "prost-derive"
version = "0.6.1"
authors = ["Dan Burkert <dan@danburkert.com>"]
license = "Apache-2.0"
repository = "https://github.com/danburkert/prost"
documentation = "https://docs.rs/prost-derive"
readme = "README.md"
description = "A Protocol Buffers implementation for the Rust Language."
edition = "2018"

[lib]
proc_macro = true

[features]
use_std = []
# std feature means that prost-derive attempts to use std collections
#
# When this feature is disabled, we attempt to use alloc.
# This should be similar to putting `config.use_alloc_collections` in a
# prost-build config
#
# Generated code assumes that user's crate has `extern crate alloc` somewhere
#
# Note that prost/std => prost-derive/std, so we don't default prost-derive/std
# This makes it so that prost with default-features = false => prost-derive
# without std.
default = []

[dependencies]
anyhow = "1"
itertools = "0.8"
proc-macro2 = "1"
quote = "1"
syn = { version = "1", features = [ "extra-traits" ] }
