[package]
name = "prost-derive"
# NB: When modifying, also modify html_root_url in lib.rs
version = "0.5.0"
authors = ["Dan Burkert <dan@danburkert.com>"]
license = "Apache-2.0"
repository = "https://github.com/danburkert/prost"
documentation = "https://docs.rs/prost-derive"
readme = "README.md"
description = "A Protocol Buffers implementation for the Rust Language."
edition = "2018"

[lib]
proc_macro = true

[features]
std = [ "failure/std" ]
# std feature means that prost-derive attempts to use std collections
#
# When this feature is disabled, we attempt to use alloc.
# This should be similar to putting `config.use_alloc_collections` in a
# prost-build config
#
# Generated code assumes that user's crate has `extern crate alloc` somewhere
default = ["std"]

[dependencies]
failure = { version = "0.1", default-features = false }
itertools = "0.8"
proc-macro2 = "0.4.4"
quote = "0.6.3"
syn = { version = "0.15", features = [ "extra-traits" ] }
